Improve collection arguments documentation for network rules
Azure/azure-cli-extensions pull request #2440
Opened 2020-09-23 09:41 UTC by TheWinch

If you specify `--priority` or `--action` in `az network firewall [network-rule|application-rule] create`, and the collection already exists, the operation will fail because it tries to recreate the collection. Make it more explicit in the documentation.

2020-09-23 09:41 UTC, azuresdkci commented
If this PR is for a new extension or change to an existing extension, use the following to try out the changes in this PR:
```
docker run -it microsoft/azure-cli:latest
export EXT=<NAME>
pip install --upgrade --target ~/.azure/cliextensions/$EXT "git+https://github.com/TheWinch/azure-cli-extensions.git@patch-1#subdirectory=src/$EXT&egg=$EXT"
```

2020-09-23 11:26 UTC, yonzhan commented
add to S176

2020-09-24 07:27 UTC, haroldrandom approved these changes

2020-09-24 08:36 UTC, haroldrandom approved these changes
@MyronFanQiu Please confirm

2020-09-24 08:46 UTC, MyronFanQiu approved these changes

2020-09-24 08:47 UTC, haroldrandom requested changes
Could you upgrade a minor verison as well. Which will trigger a new release of azure-firewall

2020-09-24 08:49 UTC, MyronFanQiu commented
You can change this [file](https://github.com/Azure/azure-cli-extensions/blob/master/src/azure-firewall/setup.py#L11) and add history into this (history)[https://github.com/Azure/azure-cli-extensions/blob/master/src/azure-firewall/HISTORY.rst]. Thanks for your contribution! 😄

2020-10-10 15:11 UTC, TheWinch commented
@haroldrandom @MyronFanQiu changes applied as requested. I took the liberty to document 0.6.1 as well, I hope I got the change right.

2020-10-11 01:11 UTC, haroldrandom approved these changes

2020-10-11 01:12 UTC, merged