Feature 15543 azure monitor control service
Azure/azure-cli-extensions pull request #2756
Opened 2020-12-07 01:17 UTC by kairu-ms

---
Close https://github.com/Azure/azure-cli/issues/15970
Close https://github.com/Azure/azure-cli/issues/15543

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2020-12-07 02:02 UTC, yonzhan commented
Monitor

2020-12-07 06:46 UTC, haroldrandom commented on src/monitor-control-service/README.md
> +az data-collection data-collection-rule-association create --association-name "myAssociation" \
This line is wrong and below

2020-12-07 06:48 UTC, haroldrandom commented on src/monitor-control-service/azext_amcs/manual/action.py
> +            raise CLIError('usage error: {} [KEY=VALUE ...]'.format(option_string))
should raise errors from azure.cli.core.azclierror

2020-12-07 06:49 UTC, haroldrandom requested changes
please fix comments above

2020-12-08 08:00 UTC, jsntcy commented on src/monitor-control-service/_az_debug/clicommon-flatten-object-map.txt
> +data_collection_rule_association_proxy_only_resource<7>
what's `_az_debug`?

2020-12-09 02:26 UTC, kairu-ms commented on src/monitor-control-service/_az_debug/clicommon-flatten-object-map.txt
> +data_collection_rule_association_proxy_only_resource<7>
removed. Thanks~

2020-12-09 08:55 UTC, haroldrandom approved these changes

2020-12-24 07:27 UTC, merged