Releasing ml 2.0.2
Azure/azure-cli-extensions pull request #4043
Opened 2021-10-28 23:46 UTC by Mossaka

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2021-11-01 21:04 UTC, Mossaka commented on src/index.json
> +                "filename": "ml-2.0.1a5-py3-none-any.whl",
changed

2021-11-01 22:38 UTC, kairu-ms approved these changes

2021-11-01 23:06 UTC, kairu-ms requested changes
The version will be changed to 2.0.2.

2021-11-02 00:19 UTC, kairu-ms approved these changes

2021-11-03 23:06 UTC, merged