Xiangy/byoc
Azure/azure-cli-extensions pull request #4091
Opened 2021-11-11 06:27 UTC by LGDoor

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2021-11-11 06:37 UTC, yonzhan commented
spring cloud

2021-11-11 11:07 UTC, bowen5 commented
Would you prepare a doc like this https://docs.microsoft.com/en-us/cli/azure/spring-cloud?view=azure-cli-latest to guide customer how to use those commands.

2021-11-12 06:10 UTC, LGDoor commented
> Would you prepare a doc like this https://docs.microsoft.com/en-us/cli/azure/spring-cloud?view=azure-cli-latest to guide customer how to use those commands.

Already added in the help.

2021-11-17 03:44 UTC, wangzelin007 reviewed
May I ask you to add some scenario tests for those new commands?
About `--registry-username <username> --registry-password <password>`, we can use mock test.

2021-12-09 09:01 UTC, LGDoor commented on src/spring-cloud/setup.py
> +VERSION = '2.11.2-container'
Updated.

2021-12-15 03:12 UTC, LGDoor commented
> May I ask you to add some scenario tests for those new commands? About `--registry-username <username> --registry-password <password>`, we can use mock test.

Hi, I've added a test case for this. Could you please review again?

2021-12-15 03:35 UTC, wangzelin007 commented
@LGDoor
Please write the description of changes into HISTORY.rst to release the new extension version.
Others look good to me.

2021-12-15 03:36 UTC, wangzelin007 requested changes
@LGDoor Xiangyang Yu FTE
Please write the description of changes into HISTORY.rst to release the new extension version.
Others look good to me.

2021-12-20 06:38 UTC, LGDoor commented
> @LGDoor Please write the description of changes into HISTORY.rst to release the new extension version. Others look good to me.

updated

2021-12-20 07:54 UTC, wangzelin007 approved these changes

2021-12-21 03:21 UTC, merged