add spring-cloud create --sku Enterprise
Azure/azure-cli-extensions pull request #4252
Opened 2021-12-22 10:55 UTC by yuwzho

---
## Description
This PR adds `az spring-cloud create --sku Enterprise` choice. Since when `sku=Enterprise`, the creation steps are very different with others (later PR will introduce some other parameters which can be used in Enterprise only), this PR adds a router before `custom.py` for create command, routing the command whose `sku==Enterprise` to another impl file. In the new impl file, there will be some steps like creating the top level resource, later creation nested resource for enterprise only. All tiers shares the same step to create top level resource, the new impl file invokes the top level resource creation impl from `custom.py` as well.

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [X] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [X] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2021-12-22 14:31 UTC, yonzhan commented
spring-cloud

2021-12-23 03:16 UTC, wangzelin007 commented on src/spring-cloud/azext_spring_cloud/_params.py
> +        c.argument('sku', arg_type=get_enum_type(['Basic', 'Standard', 'Enterprise']), validator=validate_sku, default='Standard', help='Name of SKU. Enterprise is still in Preview.')
```suggestion
sku_type = CLIArgumentType(arg_type=get_enum_type(['Basic', 'Standard', 'Enterprise']), validator=validate_sku, help='Name of SKU. Enterprise is still in Preview.')
        c.argument('sku', arg_type=sku_type, default='Standard')
```

2021-12-23 03:17 UTC, wangzelin007 commented on src/spring-cloud/azext_spring_cloud/_params.py
> +        c.argument('sku', arg_type=get_enum_type(['Basic', 'Standard', 'Enterprise']), validator=validate_sku, help='Name of SKU. Enterprise is still in Preview.')
```suggestion
        c.argument('sku', arg_type=sku_type)
```

2021-12-23 03:17 UTC, wangzelin007 requested changes
Please write the description of changes into HISTORY.rst and update setup.py to release the new extension version.

2021-12-23 05:09 UTC, yuwzho commented on src/spring-cloud/azext_spring_cloud/_params.py
> +        c.argument('sku', arg_type=get_enum_type(['Basic', 'Standard', 'Enterprise']), validator=validate_sku, default='Standard', help='Name of SKU. Enterprise is still in Preview.')
Updated

2021-12-23 05:09 UTC, yuwzho commented on src/spring-cloud/azext_spring_cloud/_params.py
> +        c.argument('sku', arg_type=get_enum_type(['Basic', 'Standard', 'Enterprise']), validator=validate_sku, help='Name of SKU. Enterprise is still in Preview.')
Updated

2021-12-23 05:11 UTC, yuwzho commented
> Please write the description of changes into HISTORY.rst and update setup.py to release the new extension version.

No, we will announce the public preview on Jan. 17th, for the public preview, we have a lot of new features contributed to CLI. Will update the release notes and version together after all changes merged.

2021-12-23 07:11 UTC, wangzelin007 approved these changes
LGTM

2021-12-23 07:50 UTC, merged

2022-01-05 03:25 UTC, yuwzho commented
#4294