Add support for host group id
Azure/azure-cli-extensions pull request #4419
Opened 2022-02-14 09:00 UTC by zjpjack

tested by running real cases
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

2022-02-14 09:02 UTC, yonzhan commented
aks

2022-02-15 03:03 UTC, FumingZhang approved these changes

2022-02-15 03:03 UTC, FumingZhang commented on src/aks-preview/HISTORY.md
> +* Add preview support for agentpools provisioned on Azure Dedicated Host Group. Requires registering the feature flag "Microsoft.ContainerService/DedicatedHostGroupPreview" for setting agentpool prop
I guess it would be better to explicitly point out that `az aks create` and `az aks nodepool add` commands support this new option `--host-group-id`?

2022-02-15 03:09 UTC, FumingZhang reviewed
Oh no, I forgot about the live test for this option.

I checked the feature validation code in rp but it does not support custom header. **In this case, we will not be able to do e2e verification from the cli side until GA (remove feature flag) or custom header is supported.**

2022-02-15 05:21 UTC, FumingZhang commented
But you may still add a live test case for this option and run in replay mode only (add the test case name to config file [ext_matrix_default.json](https://github.com/Azure/azure-cli-extensions/blob/main/src/aks-preview/azcli_aks_live_test/configs/ext_matrix_default.json)). Although this does not interact with arm/rp, it ensures that other changes will not break the passing of this option in cli side.

2022-02-15 05:22 UTC, FumingZhang requested changes

2022-02-15 05:22 UTC, FumingZhang commented on src/aks-preview/azext_aks_preview/decorator.py
> +    def get_host_group_id(self) -> Union[str, None]:
Please add unit tests for the getter functions.

2022-02-15 05:22 UTC, FumingZhang commented on src/aks-preview/azext_aks_preview/decorator.py
> +        agent_pool_profile.host_group_id = self.context.get_host_group_id()
Please add unit test for the controller function.

2022-02-16 05:56 UTC, zjpjack commented
> Oh no, I forgot about the live test for this option.
> 
> I checked the feature validation code in rp but it does not support custom header. **In this case, we will not be able to do e2e verification from the cli side until GA (remove feature flag) or custom header is supported.**

As discussed offline, I will add CustomHeader later then I can add both cli extension live test and e2e test

2022-02-16 08:12 UTC, FumingZhang approved these changes
LGTM :shipit:

2022-02-16 08:31 UTC, zhoxing-ms approved these changes

2022-02-16 08:33 UTC, zhoxing-ms commented
/azp run

2022-02-16 21:17 UTC, palma21 commented
Anything else left before merge?

2022-02-17 02:22 UTC, merged

2022-02-17 02:30 UTC, zhoxing-ms commented
@palma21 This PR has been merged