[WIP] refactor: remove redundant `--disable-workload-identity`
Azure/azure-cli-extensions pull request #4871
Opened 2022-05-23 03:40 UTC by bcho

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

2022-05-23 04:18 UTC, yonzhan commented
AKS

2022-05-23 08:06 UTC, FumingZhang approved these changes
LGTM

2022-05-23 08:45 UTC, bingosummer requested changes

2022-05-23 08:45 UTC, bingosummer commented on src/aks-preview/azext_aks_preview/_params.py
> -        c.argument('enable_workload_identity', arg_type=get_three_state_flag(), is_preview=True)
Is this expected to remove "is_preview=True"?
If so, shall we also remove it in line 367?

2022-05-23 08:49 UTC, bingosummer approved these changes

2022-05-23 10:17 UTC, bcho commented
> Please resolve CI conflicting files first.

Updated, PTAL @yonzhan

2022-05-23 10:51 UTC, zhoxing-ms commented
Will removing parameter `--disable-workload-identity` directly have a great impact on users? 
If so, can we consider using `c.deprecate(hide=True)` to hide this parameter first? When most users migrate to parameter `--enable-workload-identity False`, then we remove it completely, so as to avoid big breaking change.

2022-05-23 10:59 UTC, bcho commented
> Will removing parameter `--disable-workload-identity` directly have a great impact on users? If so, can we consider using `c.deprecate(hide=True)` to hide this parameter first? When most users migrate to parameter `--enable-workload-identity False`, then we remove it completely, so as to avoid big breaking change.

@zhoxing-ms 

Thanks for the concern. Removing these flags won't impact current user as in AKS, this feature is not being enabled yet, only a small group of testers have access to it. So, removing it won't cause breaking change.

2022-05-24 02:58 UTC, bcho commented
@zhoxing-ms @yonzhan could you help merge this pr? Thanks!

2022-05-24 03:42 UTC, zhoxing-ms approved these changes

2022-05-24 03:42 UTC, merged