[init] Refine long-summary for `az init`
Azure/azure-cli-extensions pull request #5125
Opened 2022-07-18 03:05 UTC by zhoxing-ms

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

2022-07-18 03:46 UTC, yonzhan commented
refine az init

2022-07-21 02:13 UTC, yonzhan approved these changes

2022-07-21 23:31 UTC, chasewilson requested changes
Each of these are just suggestions. Feel free to adjust as necessary :)

2022-07-21 23:31 UTC, chasewilson commented on src/init/azext_init/_help.py
> +        This tool can help you quickly know and set up global configurations that are suitable for your current usage environment:
```suggestion
        az init can help you quickly understand and set up global configurations that are suitable for your current usage environment:
```

2022-07-21 23:31 UTC, chasewilson commented on src/init/azext_init/_help.py
> +        It supports setting bundles for interactive mode and automatic mode to help you quickly set the recommended configurations.
```suggestion
        It supports setting bundles for interactive and automation scenarios to help you quickly set the recommended configurations.
```

2022-07-21 23:31 UTC, chasewilson commented on src/init/azext_init/_help.py
> +        It also supports walk through style to help you get familiar with the common configurations and customize them one by one.
```suggestion
        It also supports a walk-through experience to help you get familiar with the common configurations and customize them one by one.
```

2022-07-21 23:31 UTC, chasewilson commented on src/init/azext_init/_help.py
> +        In addition, it's purpose is not to replace the "az config" command, but to reduce the common repeated configuration behaviors by supporting setting bindles.
```suggestion
        The purpose of "az init" is not to replace the "az config" command, but to simplify common configurations by supporting setting bundles.
```

2022-07-21 23:31 UTC, chasewilson commented on src/init/azext_init/_help.py
> +        The configuration set by "az init" can also be modified by "az config", because they modify the same configuration file.
```suggestion
       While "az init" and "az config" modify the same configuration file, "az init" is aimed at an interactive, standardized approach to managing your configuration and "az config" is better at more granular control and setting configurations in automation scenarios.
```

2022-07-22 08:49 UTC, zhoxing-ms commented on src/init/azext_init/_help.py
> +       While "az init" and "az config" modify the same configuration file, "az init" is aimed at an interactive, standardized approach to managing your configuration and "az config" is better at more
```suggestion
        While "az init" and "az config" modify the same configuration file, "az init" is aimed at an interactive, standardized approach to managing your configuration and "az config" is better at more granular control and setting configurations in automation scenarios.
```

2022-07-22 08:51 UTC, zhoxing-ms commented
@chasewilson Thank you for your contribution. They look clearer and much better 😊

2022-07-22 16:40 UTC, chasewilson approved these changes

2022-07-22 16:41 UTC, chasewilson commented
@dbradish-microsoft, can you review this before merge? :)

2022-07-22 17:57 UTC, dbradish-microsoft requested changes
This command is awesome!  We need to advertise it!!  

**Format assumption:**  We can use the backtick in the long-summary.

**Feedback on the interactive instructional sentences:**
Can we please consider using active voice (i.e. an understood "you") by rewriting these statements as follows?

"This option is used to enable/disable the progress bar for long running commands" becomes "Enable/disable the progress bar for long-running commands."

"This options to enable/disable colored syntax highlighting" becomes "Enable/disable colored syntax highlighting".  If you don't update this sentence, please correct the typo by changing it to read "This option is used too ...".  This same grammar correction is needed for `message recommendations`.

**Note!**  I really like that you took the time to articulate why our customers might want to select one option over another.

2022-07-22 17:57 UTC, dbradish-microsoft commented on src/init/azext_init/_help.py
>      short-summary: It's an effortless setting up tool for configs.
short-summary: Set Azure CLI user configurations by responding to questions with multiple choice answers

long-summary: |
The Azure CLI offers `az init` to help you set global configurations through an interactive question-answer format.  Global settings are grouped into bundles that help you optimize your settings for scenarios such as "interaction" or "automation".  To familiarize yourself with common configurations and select available options, answer the step-by-step questions, and `az init` will do the rest!

The purpose of `az init` is not to replace the `az config` command, but to simplify the setting of configurations by offering an interactive question-answer experience.  While both `az inti` and `az config` modify the same configuration file, `az init` is designed to only set the most common configurations.  For more granular control of all available configurations, use `az config`.  For more information on configuring your Azure CLI environment, see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration.

2022-07-22 18:49 UTC, dbradish-microsoft commented on src/init/azext_init/_help.py
>      short-summary: It's an effortless setting up tool for configs.
```suggestion
    short-summary: Set Azure CLI user configurations by responding to questions with multiple choice answers.
```

2022-07-22 18:50 UTC, dbradish-microsoft commented on src/init/azext_init/_help.py
> +    long-summary: |
long-summary: |
The Azure CLI offers `az init` to help you set global configurations through an interactive question-answer format.  Global settings are grouped into bundles that help you optimize your settings for scenarios such as "interaction" or "automation".  To familiarize yourself with common configurations and select available options, answer the step-by-step questions, and `az init` will do the rest!

The purpose of `az init` is not to replace the `az config` command, but to simplify the setting of configurations by offering an interactive question-answer experience.  While both `az inti` and `az config` modify the same configuration file, `az init` is designed to only set the most common configurations.  For more granular control of all available configurations, use `az config`.  For more information on configuring your Azure CLI environment, see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration.

2022-07-22 18:51 UTC, dbradish-microsoft commented on src/init/azext_init/_help.py
> +    long-summary: |
```suggestion
long-summary: |
The Azure CLI offers `az init` to help you set global configurations through an interactive question-answer format.  Global settings are grouped into bundles that help you optimize your settings for scenarios such as "interaction" or "automation".  To familiarize yourself with common configurations and select available options, answer the step-by-step questions, and `az init` will do the rest!

The purpose of `az init` is not to replace the `az config` command, but to simplify the setting of configurations by offering an interactive question-answer experience.  While both `az inti` and `az config` modify the same configuration file, `az init` is designed to only set the most common configurations.  For more granular control of all available configurations, use `az config`.  For more information on configuring your Azure CLI environment, see https://docs.microsoft.com/en-us/cli/azure/azure-cli-configuration.
```

2022-07-25 06:40 UTC, zhoxing-ms commented
@dbradish-microsoft Thank you for putting forward so many valuable and valuable suggestions!
I have updated the summary message based on your comments and Chase's comments

2022-07-25 15:34 UTC, dbradish-microsoft requested changes
The majority of our short-summary values are in the active voice with an understood "you".  So "<you> Manage ..." or "<you> Configure...".  Our short-summary values will all be standardized this way in fall 2022 under work item [1953041](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1953041).

@Chasewilson, please advise if you would prefer a different active-voice phrase.

2022-07-25 15:34 UTC, dbradish-microsoft commented on src/init/azext_init/_help.py
> +short-summary: It's an effortless setting up tool for configs by offering an interactive question-answer experience
```suggestion
short-summary: Set Azure CLI user configurations by responding to questions with multiple choice answers.
```

2022-07-25 16:44 UTC, chasewilson commented
> The majority of our short-summary values are in the active voice with an understood "you". So "<you> Manage ..." or "<you> Configure...". Our short-summary values will all be standardized this way in fall 2022 under work item [1953041](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1953041).
> 
> @chasewilson, please advise if you would prefer a different active-voice phrase.

I believe the docs guidance is that we should use active voice as much as possible and should try and stay consistent.

2022-08-01 07:54 UTC, zhoxing-ms commented
@dbradish-microsoft Thank you for your detailed explanation. I agree that the active voice should be used in `short-summary` to keep consistency. 
I have updated the `short-summary`, please help review again, thank you

2022-09-05 05:43 UTC, jsntcy approved these changes

2022-09-06 19:55 UTC, dbradish-microsoft approved these changes

2022-09-19 08:01 UTC, merged