{AzureContainerApp} fixes Azure/azure-cli-extensions#5781 fix for 'NoneType' object does not support item assignment
Azure/azure-cli-extensions pull request #5791
Opened 2023-01-19 09:21 UTC by navba-MSFT

fixes Azure/azure-cli-extensions#5781

fix for TypeError: 'NoneType' object does not support item assignment while running the `az containerapp dapr enable` command

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repository and upgrade the version in the pull request but do not modify `src/index.json`.

2023-01-19 09:42 UTC, yonzhan commented
AzureContainerApp

2023-01-21 00:07 UTC, vinisoto approved these changes

2023-01-22 19:16 UTC, calleo commented
Hi, I've submitted as PR for this problem here: https://github.com/Azure/azure-cli-extensions/pull/5782

2023-01-23 19:27 UTC, StrawnSC requested changes
I still get an error when I try to use this code for enabling dapr: 
<img width="1073" alt="Screen Shot 2023-01-23 at 11 24 25 AM" src="https://user-images.githubusercontent.com/10121214/214130992-65c56ea7-e1f8-4901-b007-ef168a0600e8.png">

We should add `safe_get`s in lines 2371 and 2374 with a `default=[]` so that we don't get "None type is not iterable" errors

2023-01-31 02:11 UTC, Juliehzl commented
could you try to add test for the none type scenario in https://github.com/Azure/azure-cli-extensions/blob/main/src/containerapp/azext_containerapp/tests/latest/test_containerapp_commands.py#L583

2023-01-31 05:03 UTC, Juliehzl approved these changes
make sure command work

2023-02-01 08:31 UTC, zhoxing-ms commented
@navba-MSFT Could you please resolve these CI issues?

2023-02-02 04:03 UTC, closed without merging