Adding ExtensionImage + Aaz + Assess-Patches
Azure/azure-cli-extensions pull request #6253
Opened 2023-05-02 18:25 UTC by ankjayant

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

First time using connectedmachine with aaz-dev-tools. We generated existing commands and resources as well two new commands. az connectedmahcine extensionimage and az connectedmahcine assess-patches. 

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2023-05-02 18:26 UTC, yonzhan commented
<!-- add-pr-comment:add-pr-comment -->

Thank you for your contribution! We will review the pull request and get back to you soon.

2023-05-11 21:47 UTC, ankjayant commented
> Hi @ankjayant, If you want to release the new extension version. Please write the description of changes into HISTORY.rst and update setup.py.

Updated these files

2023-05-11 21:47 UTC, ankjayant commented
> Thank you for your contribution! We will review the pull request and get back to you soon.

Hey - still looking for a review

2023-05-12 02:58 UTC, kairu-ms commented on src/connectedmachine/setup.py
> +VERSION = '0.6.1'
Why skip version 0.6.0?

2023-05-12 03:00 UTC, kairu-ms commented on src/connectedmachine/azext_connectedmachine/aaz/latest/connectedmachine/_install_patches.py
> +    """The operation to install patches on a hybrid machine identity in Azure.
Please add examples for these commands in aaz-dev-tools

2023-05-12 03:04 UTC, kairu-ms requested changes
Please add tests for those new commands

2023-05-25 21:19 UTC, ankjayant commented on src/connectedmachine/setup.py
> +VERSION = '0.6.1'
fixed this

2023-05-31 03:54 UTC, kairu-ms commented
@ankjayant, it seems you removed the tests files.

2023-06-26 19:16 UTC, yaotongms commented
> @ankjayant, it seems you removed the tests files.

Hello Kairu, my name is Yao. Ankit is no longer in Microsoft, and I will be taking over his work. I'm trying to merge this PR into azure cli extension and saw your comment on adding test files to the commands. I have some questions that I hope you can answer.

- Can I just add back all the tests he deleted?
- If not, do I need to start over from exporting the command tree to aaz repo, generate the cli commands and then start a new PR?

2023-06-27 01:14 UTC, kairu-ms commented
> > @ankjayant, it seems you removed the tests files.
> 
> Hello Kairu, my name is Yao. Ankit is no longer in Microsoft, and I will be taking over his work. I'm trying to merge this PR into azure cli extension and saw your comment on adding test files to the commands. I have some questions that I hope you can answer.
> 
> * Can I just add back all the tests he deleted?
> * If not, do I need to start over from exporting the command tree to aaz repo, generate the cli commands and then start a new PR?
> * I registered my github account with my microsoft email but don't have permission to push changes to aaz or az-cli-extension. I wonder if I need to obtain permission from someone.

2023-06-27 02:20 UTC, kairu-ms commented
> > @ankjayant, it seems you removed the tests files.
> 
> Hello Kairu, my name is Yao. Ankit is no longer in Microsoft, and I will be taking over his work. I'm trying to merge this PR into azure cli extension and saw your comment on adding test files to the commands. I have some questions that I hope you can answer.
> 
> * Can I just add back all the tests he deleted?
> * If not, do I need to start over from exporting the command tree to aaz repo, generate the cli commands and then start a new PR?
> * I registered my github account with my microsoft email but don't have permission to push changes to aaz or az-cli-extension. I wonder if I need to obtain permission from someone.

Hi @yaotongms
* This PR is not merged. So you can add back all the tests from the main branch or from the previous commits.
* @ankjayant has submit his change of aaz-model in this PR https://github.com/Azure/aaz/pull/189, you can pull his change and continue.
* The aaz and azure-cli-extensions repos are not allowed to push directly. You should fork these repo and push changes in your forked repo. Then create a PR from your forked repo to these repos

2023-06-27 18:37 UTC, yaotongms commented
> 

Hello Kairu, thanks for the info! 

If I understand it correctly, this PR needs tests to be added back. Are those generated when generating the cli command on the aaz ui?

Moreover, Ankit's aaz repo seems to have some conflicts that needs to be resolved and need another reviewer to review it. I don't seem to have the write access to it so I'm not sure what the conflict is.

If it's more convenient, I can generate the extensionimage command again and have another PR since I'm not sure why Ankit removed those tests.

2023-06-28 01:50 UTC, kairu-ms commented
> > 
> 
> Hello Kairu, thanks for the info!
> 
> If I understand it correctly, this PR needs tests to be added back. Are those generated when generating the cli command on the aaz ui?
> 
> Moreover, Ankit's aaz repo seems to have some conflicts that needs to be resolved and need another reviewer to review it. I don't seem to have the write access to it so I'm not sure what the conflict is.
> 
> If it's more convenient, I can generate the extensionimage command again and have another PR since I'm not sure why Ankit removed those tests.



> > 
> 
> Hello Kairu, thanks for the info!
> 
> If I understand it correctly, this PR needs tests to be added back. Are those generated when generating the cli command on the aaz ui?
> 
> Moreover, Ankit's aaz repo seems to have some conflicts that needs to be resolved and need another reviewer to review it. I don't seem to have the write access to it so I'm not sure what the conflict is.
> 
> If it's more convenient, I can generate the extensionimage command again and have another PR since I'm not sure why Ankit removed those tests.

Yes, you can regenerate the commands again. There are some tips can help, maybe we could have a quick call.

2023-09-15 01:14 UTC, closed without merging