[Elastic] Bump up `elastic` API version to `2023-02-01-preview`
Azure/azure-cli-extensions pull request #6324
Opened 2023-05-25 09:37 UTC by Jing-song

---
Bump up `elastic` API version to `2023-02-01-preview`
AAZ model https://github.com/Azure/aaz/pull/198
close https://github.com/Azure/azure-cli/issues/24618

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2023-05-25 09:37 UTC, yonzhan commented
<!-- add-pr-comment:add-pr-comment -->

Elastic

2023-07-06 08:45 UTC, kairu-ms commented on src/elastic/azext_elastic/azext_metadata.json
> +    "azext.minCliCoreVersion": "2.48.0"
```suggestion
    "azext.minCliCoreVersion": "2.49.0"
```

2023-07-06 08:50 UTC, kairu-ms commented on src/elastic/azext_elastic/aaz/latest/elastic/monitor/tag_rule/_create.py
> +        az elastic monitor tag-rule create -n default -g rg --monitor-name monitor --log-rules {filteringTags:[{name:Environment,value:Prod,action:Include}]}
```suggestion
        az elastic monitor tag-rule create -n default -g rg --monitor-name monitor --log-rules "{filteringTags:[{name:Environment,value:Prod,action:Include}]}"
```

2023-07-07 02:31 UTC, kairu-ms approved these changes

2023-07-07 02:42 UTC, kairu-ms requested changes

2023-07-07 02:42 UTC, kairu-ms commented on src/elastic/HISTORY.rst
> +1.0.0
```suggestion
1.0.0b1
```

2023-07-07 02:42 UTC, kairu-ms commented on src/elastic/setup.py
> +VERSION = '1.0.0'
```suggestion
VERSION = '1.0.0b1'
```

2023-07-07 03:17 UTC, kairu-ms approved these changes

2023-07-07 05:39 UTC, merged