az network bastion rdp fails with NullPointerException
Azure/azure-cli-extensions pull request #6514
Opened 2023-07-13 09:36 UTC by navba-MSFT

fixes Azure/azure-cli-extensions#6478

`az network bastion rdp --name "" --resource-group "" --target-resource-id "" --disable-gateway` fails with below error:
```
Exception in thread Thread-1 (_start_tunnel):
Traceback (most recent call last):
File "threading.py", line 1016, in _bootstrap_inner
File "threading.py", line 953, in run
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\custom.py", line 335, in _start_tunnel
tunnel_server.start_server()
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\tunnel.py", line 194, in start_server
self._listen()
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\tunnel.py", line 123, in _listen
auth_token = self._get_auth_token()
File "C:\Users\francisco.nabas.azure\cliextensions\bastion\azext_bastion\tunnel.py", line 110, in _get_auth_token
raise exp
msrestazure.azure_exceptions.CloudError: java.lang.NullPointerException
```
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2023-07-13 09:36 UTC, yonzhan commented
<!-- add-pr-comment:add-pr-comment -->

Thank you for your contribution! We will review the pull request and get back to you soon.

2023-07-18 07:27 UTC, necusjz commented
> @necusjz Could you please review this once you get a chance ?

@navba-MSFT, if you wanna release a new version including this fix, please update `HISTORY.rst` and `setup.py` as well.

2023-07-18 08:28 UTC, necusjz requested changes
@navba-MSFT, if you wanna release a new version including this fix, please update `HISTORY.rst` and `setup.py` as well.

2023-07-19 07:49 UTC, necusjz approved these changes

2023-07-19 07:51 UTC, merged