[az fleet] updated help examples
Azure/azure-cli-extensions pull request #6995
Opened 2023-11-14 17:49 UTC by Ealianis

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
Updated help text examples for `az fleet`

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2023-11-14 17:50 UTC, yonzhan commented
<!-- add-pr-comment:add-pr-comment -->

az fleet

2023-11-14 23:22 UTC, jim-minter requested changes

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Delete a specific fleet member
```suggestion
        - name: Delete a specific fleet member.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Show the details of a specific updaterun
```suggestion
        - name: Show the details of a specific update run.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +          text: az fleet list -g MyResourceGroup
```suggestion
        - name: List all fleets that exist within a specific subscription.
          text: az fleet list
        - name: List all fleets that exist within a specific subscription and resource group.
          text: az fleet list -g MyResourceGroup
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Show the details of a specific updaterun
```suggestion
        - name: Show the details of a specific update run.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Delete a specific updaterun.
```suggestion
        - name: Delete a specific update run.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Starts an updaterun
```suggestion
        - name: Starts an update run.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Stops an updaterun
```suggestion
        - name: Stops an update run.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Create an updatestrategy from a JSON file.
```suggestion
        - name: Create an update strategy from a JSON file.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Show the details of a specific updatestrategy.
```suggestion
        - name: Show the details of a specific update strategy.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: List all updatestratgies for a given fleet.
```suggestion
        - name: List all update strategies for a given fleet.
```

2023-11-14 23:22 UTC, jim-minter commented on src/fleet/azext_fleet/_help.py
> +        - name: Delete a specific updatestrategy.
```suggestion
        - name: Delete a specific update strategy.
```

2023-11-16 03:07 UTC, kairu-ms approved these changes

2023-11-16 03:08 UTC, merged