[az fleet] Minor style & linter updates to fix checks.
Azure/azure-cli-extensions pull request #7092
Opened 2023-12-15 18:05 UTC by Ealianis

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
`az fleet`

### General Guidelines

- [x] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [x] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)

For new extensions:

- [x] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2023-12-15 18:05 UTC, yonzhan commented
<!-- add-pr-comment:add-pr-comment -->

az fleet

2023-12-15 21:58 UTC, jim-minter commented on src/fleet/azext_fleet/_completers.py
> +        warn(f'Warning: {err.meesage}')
```suggestion
        warn(f'Warning: {err.message}')
```

2023-12-15 22:01 UTC, jim-minter commented on src/fleet/azext_fleet/_helpers.py
> +    return None
instead of returning None, does it work instead to `raise` in the (IOError, OSError) case if the error isn't ENOENT?

2023-12-15 22:02 UTC, jim-minter requested changes
Just those two comments then good to merge.

2023-12-15 22:46 UTC, jim-minter approved these changes
LGTM!

2023-12-18 02:13 UTC, kairu-ms approved these changes

2023-12-18 02:13 UTC, merged