vm repair changes to support repair for cvm
Azure/azure-cli-extensions pull request #7821
Opened 2024-07-23 04:55 UTC by dkulkarni-ms

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command
az vm repair create -g RG -n VM --unlock-encrypted-vm --encrypted-vm-recovery-password "***" 
Above command creates confidential rescue VM. 

az vm repair run -g RG -n VM --run-id win-crowdstrike-fix-bootloop-cvm --run-on-repair
This to run script on disk. 

az vm repair restore -g RG -n VM  --verbose --debug> debugoutput

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2024-07-23 04:56 UTC, yonzhan commented
<!-- add-pr-comment:prcommentbot -->

Thank you for your contribution! We will review the pull request and get back to you soon.

2024-07-23 08:40 UTC, canfikret requested changes

2024-07-23 19:33 UTC, dkulkarni-ms commented on src/vm-repair/azext_vm_repair/repair_utils.py
> +        return _invoke_run_command(WINDOWS_RUN_SCRIPT_NAME, repair_vm_name, repair_group_name, False, parameters=BITLOCKER_RECOVERY_PARAMS)
I had tested this scenario of wrong recovery password, the entire script fails and writes error. May be I will raise exception if script fails and fail entire create command.

2024-07-23 19:33 UTC, dkulkarni-ms commented on src/vm-repair/azext_vm_repair/_params.py
> +        c.argument('encrypted_vm_recovery_password', help='Option to auto-unlock encrypted VMs using current subscription auth.')
Changing

2024-07-23 19:35 UTC, dkulkarni-ms commented on src/vm-repair/azext_vm_repair/repair_utils.py
> +        raise WindowsOsNotAvailableError()
I am thinking to do this logic - 
If source vm os sku has gen2 or g2 then use specific 2022 datacenter gen 2 as sku
else will use specific 2022 datacenter gen1
 
That way it should work for both TVM and CVM.

2024-07-24 00:16 UTC, dkulkarni-ms commented on src/vm-repair/azext_vm_repair/repair_utils.py
> +        return _invoke_run_command(WINDOWS_RUN_SCRIPT_NAME, repair_vm_name, repair_group_name, False, parameters=BITLOCKER_RECOVERY_PARAMS)
I have added to exit resource and clean up resource if the password is wrong.

2024-07-24 00:17 UTC, dkulkarni-ms commented on src/vm-repair/azext_vm_repair/repair_utils.py
> +        raise WindowsOsNotAvailableError()
Made necessary changes

2024-08-15 15:01 UTC, closed without merging