Networkcloud 20240701preview version updated
Azure/azure-cli-extensions pull request #8291
Opened 2024-11-15 22:37 UTC by priyamshet

---

This checklist is used to make sure that common guidelines for a pull request are followed.

### Related command

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally? (`pip install wheel==0.30.0` required)
- [ ] My extension version conforms to the [Extension version schema](https://github.com/Azure/azure-cli/blob/release/doc/extensions/versioning_guidelines.md)

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your pull request is merged into main branch, a new pull request will be created to update `src/index.json` automatically.  
You only need to update the version information in file setup.py and historical information in file HISTORY.rst in your PR but do not modify `src/index.json`.

2024-11-15 22:50 UTC, mbashtovaya commented on src/networkcloud/HISTORY.rst
> +* Validation is added to `--command-output-settings` property of a cluster for both create and update commands. When the identityType is SystemAssignedIdentity, the UAI should not be provided.
remove - duplicate info

2024-11-15 22:51 UTC, mbashtovaya requested changes
release history needs to be updated

2024-11-15 23:05 UTC, yonzhan commented
Networkcloud

2024-11-15 23:23 UTC, mbashtovaya approved these changes

2024-11-19 19:14 UTC, mbashtovaya approved these changes

2024-11-20 02:32 UTC, necusjz commented
/azp run

2024-11-20 02:43 UTC, necusjz approved these changes

2024-11-20 02:45 UTC, merged